### ISSUE TITLE
fetch wrapper adds a Content-Type header alongside a lowercased content-type header from the request

### ISSUE THREAD

**Issue by maxnachlinger** [alexghr/got-fetch#15]
Stating the obvious here, but [HTTP headers are not case sensitive](https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2) :) [These lines](https://github.com/alexghr/got-fetch/blob/master/src/lib/fetch.ts#L65-L68) are great in that any headers specified in the request override the ones calculated in [`serializeBody`](https://github.com/alexghr/got-fetch/blob/5bd7db37416e7ebc8920fb96aeb9a2f3f688d472/src/lib/fetch.ts#L98).
```typescript
gotOpts.headers = {
  ...bodyHeaders,
  ...(request.headers as object)
};
```
The problem occurs when the headers specified in the request don't match the casing, e.g.:
```javascript
const bodyHeaders = { 'Content-Type': 'application/octet-stream' };
const request = { headers: { 'content-type': 'application/json' } };
{ ...bodyHeaders, ...request.headers }
/*
Results in:
{
  'Content-Type': 'application/octet-stream',
  'content-type': 'application/json'
}
*/
```
I'll be happy to submit a PR for this. IMHO the easiest way out is to lowercase the headers sent back from `serializeBody` and lowercase the headers sent in the request.

**Comment by Revadike** [comment]
Yes, currently we cannot set the content-type header ourselves.

**Comment by alexghr** [comment]
@Revadike what version of the library and node are you running into this issue on? I've tried reproducing this in a test and, at least on v5 of got-fetch, I'm able to overwrite `Content-Type` regardless of casing

**Comment by Revadike** [comment]
I used v4, because I like to use requirejs.
