### ISSUE TITLE
Stream body support?

### ISSUE THREAD

**Issue by wmertens** [alexghr/got-fetch#25]
Hi, I'm scoping out your library :)

When looking at [response.ts](https://github.com/alexghr/got-fetch/blob/8aac98fbf102de3a40c2a486bda129c910a60f65/src/lib/response.ts#L89-L91) it seems that if the body is a stream, that's not supported, right? I'm new to `got` so not sure how streams work.

If that's the case, would that be solved by using the [`consumeBody`](https://github.com/node-fetch/node-fetch/blob/51861e98a8f87e0905e71bb101b506f9512a9d7f/src/body.js#L160-L227) function from `node-fetch`?

**Comment by wmertens** [comment]
Awesome, thanks! :)

**Comment by alexghr** [comment]
Ha, wasn't sure if you were still interested in this after ... 7-8 months. I've published it under the `next` tag on npm. If you do end up trying it, could you let me know how/if it works for your use case? I've discovered a couple of issues with got's stream handling while working on this.
