### ISSUE TITLE
Could we add support for got v13?

### ISSUE THREAD

**Issue by JaneJeon** [alexghr/got-fetch#373]
I saw https://github.com/alexghr/got-fetch/pull/344, but I was wondering if we could widen the range of peerdeps to include got v13 as well?

There is virtually no difference between v13 and v12, except for dropping an old version of node: https://github.com/sindresorhus/got/releases/tag/v13.0.0

Would appreciate it, thank you :)

**Comment by Johann-S** [comment]
I think now we can ask for v14 😅

**Comment by alexghr** [comment]
hahah, if you someone would open a PR, I'd be open to merge it in.

**Comment by Johann-S** [comment]
@alexghr I gave it a shot!
