### ISSUE TITLE
Final URL

### ISSUE THREAD

**Issue by Revadike** [alexghr/got-fetch#49]
Is there a way to get the final URL?

**Comment by alexghr** [comment]
It _should_ be the url you pass in to the function. Are you seeing differences between your parameters and what gets hit by the HTTP client?

**Comment by Revadike** [comment]
When a redirect occurs, the final URL is usually different from the initial request URL.

**Comment by alexghr** [comment]
Oh right, I see what you mean. It's meant to be available on the response object but I see now that I passed the original URL rather than the final URL

https://github.com/alexghr/got-fetch/blob/38fc12b50d911ca91c46285686d4f5cf2bfee179/src/lib/fetch.ts#L87-L92

**Comment by alexghr** [comment]
As of v4.0.2 the `Reponse.url` property now points to the final URL after all redirects.

@Revadike lmk if this fix is enough to close this ticket.

**Comment by Revadike** [comment]
Yeah, I believe so. Thanks!
