### ISSUE TITLE
Support unix domain sockets

### ISSUE THREAD

**Issue by gwn** [alexghr/got-fetch#7]
Hello,

Thanks for this library.

I switched from `node-fetch` because it doesn't support unix domain sockets. While I was looking for a fetch compatible alternative, I found this, only to realize that this doesn't support unix domain sockets either! (Although `got` does)

https://github.com/sindresorhus/got#unix-domain-sockets

**Comment by alexghr** [comment]
Interesting 🤔

What error are you seeing? My initial thought was that `URL` wouldn't parse unix domain sockets but it does seem to parse them correctly...

**Comment by gwn** [comment]
`got` accepts two types of strings for unix domain sockets, `http://unix:...` and `unix:/...`.
`URL` rejects the first form but accepts the second so we're fine.

I just realized that `got` is throwing an exception when using the second form, at least in my platform. So it is not related to `got-fetch`.

I guess I'll raise the issue in `got`s repo instead.

Wrong alarm, sorry :)

**Comment by gwn** [comment]
Turns out that it was not a wrong alarm :)

Bot `got` and `got-fetch` need to be patched to enable UNIX domain socket support.

I sent a PR
https://github.com/alexghr/got-fetch/pull/8

**Comment by gwn** [comment]
Fixed as #8 is merged.

**Comment by alexghr** [comment]
Released in v2.0.2
